from . import res_partner
from . import ks_project_inherit
from . import ks_project_task
from . import ks_survey_user_input
from . import ks_survey_inherit
from . import survey_user_input_line_inherit
from . import link_project_survey
from . import company_inherit
from . import account_analytic_line_inherit
from . import planning_slot_inherit
from . import sms_template
from . import sms_composer_inherit
from . import automate_program_type
from . import planning_slot_template_inherit
from . import ks_product_template
from . import ks_modifiers
from . import ks_procedure_code
from . import ks_hr_employee
from . import ks_logger
from . import ks_planning_slot_inherit
from . import res_partner_leaving_reason
from . import ks_progress_notes
from . import ks_specialisty
from . import ks_document_folder_inherit
from . import ks_mail_activity_type
from . import ks_project_task_type

